version: "3.7"

networks:
  front-tier:
    name: front-tier
    driver: overlay
    attachable: true
    ipam:
      config:
        - subnet: 70.28.0.0/16
#        - gateway: 70.28.5.254
  back-tier:
    name: back-tier
    driver: overlay
    attachable: true
 
services:
  mysql:
    image: docker.viraweb123.ir/mysql
    hostname: mysql
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: 
          - node.labels.disk == ssd
      replicas: 1
    labels:
      com.dgyar.description: "Data node"
      com.dgyar.department: "IT"
    command: --sql_mode=""
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: plufdb
      MYSQL_USER: pluf
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    networks:
      - back-tier
    volumes:
      - "/mnt/mysql:/var/lib/mysql"
  pluf:
    image: docker.viraweb123.ir/pluf
    hostname: pluf
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: 
          - node.labels.type == gateway
      mode: global
    labels:
      com.dgyar.description: "Public webapp interface"
      com.dgyar.department: "IT"
    volumes:
      - "/mnt/storage:/var/www/storage"
 #     - "/mnt/logs:/var/www/logs"
      - "/mnt/apache:/etc/apache2"
      - "/mnt/letsencrypt:/etc/letsencrypt"
    ports:
      - "80:80"
      - "443:443"
    networks:
#      - front-tier
      - back-tier
    depends_on:
      - mysql


